<?php /* Smarty version 2.6.18, created on 2012-12-26 13:25:18
         compiled from file:/homepage/OPENPNESAAJ/ossi_pne/webapp/modules/admin/templates/inc_subnavi_adminStatisticalInformation.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 't_escape', 'file:/homepage/OPENPNESAAJ/ossi_pne/webapp/modules/admin/templates/inc_subnavi_adminStatisticalInformation.tpl', 3, false),)), $this); ?>
<div class="subNavi">
<?php echo '<a href="?m='; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['module_name']); ?><?php echo '&amp;a=page_'; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['hash_tbl']->hash('user_analysis_generation')); ?><?php echo '">世代別メンバー数表示</a>&nbsp;|&nbsp;<a href="?m='; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['module_name']); ?><?php echo '&amp;a=page_'; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['hash_tbl']->hash('user_analysis_date_month')); ?><?php echo '">登録日別メンバー数表示（月次集計）</a>&nbsp;|&nbsp;<a href="?m='; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['module_name']); ?><?php echo '&amp;a=page_'; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['hash_tbl']->hash('user_analysis_date_day')); ?><?php echo '">登録日別メンバー数表示（日次集計）</a>&nbsp;|&nbsp;'; ?><?php $_from = $this->_tpl_vars['profile_list']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['item']):
?><?php echo '<a href="?m='; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['module_name']); ?><?php echo '&amp;a=page_'; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['hash_tbl']->hash('user_analysis_profile')); ?><?php echo '&target_c_profile_id='; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['item']['c_profile_id']); ?><?php echo '">'; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['item']['caption']); ?><?php echo '別メンバー数表示</a>&nbsp;|&nbsp;'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php if (@LOG_C_ACCESS_LOG): ?><?php echo '<a href="?m='; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['module_name']); ?><?php echo '&amp;a=page_'; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['hash_tbl']->hash('access_analysis_month')); ?><?php echo '&ktai_flag=0">PCページ月次集計</a>&nbsp;|&nbsp;<a href="?m='; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['module_name']); ?><?php echo '&amp;a=page_'; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['hash_tbl']->hash('access_analysis_month')); ?><?php echo '&ktai_flag=1">携帯ページ月次集計</a>&nbsp;|&nbsp;'; ?><?php endif; ?><?php echo '<a href="?m='; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['module_name']); ?><?php echo '&amp;a=page_'; ?><?php echo smarty_modifier_t_escape($this->_tpl_vars['hash_tbl']->hash('image_analysis_category')); ?><?php echo '">カテゴリ別画像容量表示</a>&nbsp;|&nbsp;'; ?>

</div>